name: L1LLPJetTagger
channels:
  - conda-forge
dependencies:
  - uproot
  - coffea>=2024.4.0
  - hist>=2.6.0
  - boost-histogram
  - awkward>=2.6.0
  - pandas
  - ipykernel
  - notebook
  - python=3.10
  - numpy=1.24
  - tqdm
  - h5py
  - pytest
  - black=24.4.2
  - ruff=0.4.6
  - pip
  - pip:
      - mypy
