[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "L1LLPJetTagger"
version = "0.1.0"
description = "A sample project"
authors = [{ name = "Daniel Diaz", email = "d4diaz@ucsd.edu" }]
dependencies = []

[tool.setuptools]
packages = { find = { where = ["src"] } }

[tool.black]
line-length = 88
target-version = ['py310']

[tool.ruff]
line-length = 88
target-version = "py310"
